spring:
  application:
    name: ms-order


  # JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: 2004
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: 8081

springdoc:
  swagger-ui:
    url: /openapi.yaml