version: '3.8'

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004  
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ms-stock:
    build: 
      context: .
    container_name: ms-stock
    ports: 
      - 8080:8080