spring:
  application:
    name: ms-stock

  # JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: postgres
    password: 2004
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

