openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /api/v1/order:
    post:
      tags:
        - order-controller
      summary: Create a new order
      description: Creates a new order in the system.
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        '201':
          description: Order created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request data
  /api/v1/order/historic/{email}:
    get:
      tags:
        - order-controller
      summary: Find orders by email
      description: Fetches all orders associated with a email.
      operationId: findOrdersByEmail
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Orders retrieved successfully
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: No orders found for the email
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        clientEmail:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        quantity:
          type: integer
          format: int32
