name: Build Maven for Target

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven ms-client
      working-directory: ./ms-client
      run: mvn clean package

    - name: Build with Maven ms-order
      working-directory: ./ms-order
      run: mvn clean package

    - name: Build with Maven ms-stock
      working-directory: ./ms-stock
      run: mvn clean package
